### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by dahong67** [dahong67/ConvolutionalOperatorLearning.jl#1]
Non-exhaustive list:
+ [x] R1 x R2 filters, i.e., rectangular filters
+ [x] 1d filters/data
+ [x] 3d filters/data
+ [x] even-sized filters

**Comment by cecroc** [comment]
Rectangular filters: The reference version of CAOL does not support rectangular filters, so the test for rectangular filters is simply making sure that the objective function is decreasing (to within a tolerance based on machine precision) and that the returned filter matrix is the same for both of the CAOL signatures.

**Comment by cecroc** [comment]
Mis-matched filter and data dimensions: 

As written, the code was in an infinite loop calling the signature 
CAOL(X::AbstractArray,λ::Real,H0R::SignalTuple; p=0,maxiters=2000,tol=1e-13,trace=false) =
    CAOL(_extractsignals(X),λ,H0R; p=p,maxiters=maxiters,tol=tol,trace=trace)

I've changed the signature below such that N and M can be different to land in the function, then throw an error if they are. I'm not sure if this will obviate the usefulness of the above signature though - I wasn't able to figure out when that signature was needed. 

function CAOL(x::SignalBank{N},λ::Real,h0::SignalBank{M};
        p=0,maxiters=2000,tol=1e-13,trace=false) where {N,M}
    @assert N == M "Signal dimension must match filter dimension"

**Comment by cecroc** [comment]
All signatures: 

I've added tests that cover all combinations of: 
input can be x (vectorized) or X (matrix form) 
filters can be h (vectorized) or H (matrix form) 
trace setting can be off (default) or on

**Comment by cecroc** [comment]
Convergence: 

Added a test (only 2d) to make sure all signatures match the reference when converging before the maximum number of iterations.
