### ISSUE TITLE
Add more initialization filters

### ISSUE THREAD

**Issue by dahong67** [dahong67/ConvolutionalOperatorLearning.jl#2]
Non-exhaustive list:
+ [x] DCT for arbitrary dimension (2D is done)
+ [ ] EFD
+ [x] rectangular versions

Also add other convenience signatures. Some candidates:
+ `generatefilters(filt_type, filt_dim, filt_size as an int)`
+ `generatefilters(filt_type, filt_size as a tuple)`

Ref: `src/filters.jl`.

Will likely involve also adding (but probably not exporting) helper functions for things like gram schmidt, and "snake" ordering.

**Comment by dahong67** [comment]
Note: EFD might have some rank/orthogonality issues. Notably,

```julia
using FFTW, LinearAlgebra

R = 7

temp = dct(Matrix(I,R,R),1)
H = kron(temp,temp)'./R

h = reshape(H,R,R,R^2)
h[:,:,2:5] = zeros(R,R,4)
h[1,1,2] = 1; h[2,1,2] = -1 # vertical differences filter
h[1,2,3] = 1; h[1,3,3] = -1 # horizontal differences filter
h[2,2,4] = 1; h[3,3,4] = -1 # diagonal top-left to bottom-right
h[2,3,5] = 1; h[3,2,5] = -1 # diagonal top-right to bottom-left

rank(H) < R^2
```

This appears to then cause issues when we run Gram-Schmidt
```julia
function gramschmidt(V)
    (n,k) = size(V)
    U = zeros(n,k);
    U[:,1] = V[:,1]/sqrt(V[:,1]'*V[:,1]);
    for i = 2:k
      U[:,i] = V[:,i];
      for j = 1:i-1
        U[:,i] = U[:,i] - ( U[:,i]'*U[:,j] )/( U[:,j]'*U[:,j] )*U[:,j];
      end
      U[:,i] = U[:,i]/sqrt(U[:,i]'*U[:,i]);
    end
    return U
end

H = gramschmidt(H)
extrema(triu(H'H,1)) == (-0.3441422725049603, 0.36486864918825357)
```

**Comment by cecroc** [comment]
We talked about this a while back, but I don't think it makes sense to have a general :EFD option for arbitrary dimensions. In the interest of keeping the code generalizable, my suggestion is we only have the :DCT option for now. We can always go back and add something later if it becomes useful. 

:DCT currently works for rectangular filters as well. So, I will close this issue, but feel free to re-open if you think we should offer something other than :DCT.
